# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exp2.Asset')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('scenario_file', models.FileField(upload_to=dt.models.scenario_upload_path)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='exp2.Experiment')),
            ],
            bases=('exp2.asset',),
        ),
    ]
