# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exp2.Asset')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            bases=('exp2.asset',),
        ),
        migrations.CreateModel(
            name='QuizTask',
            fields=[
                ('experimentaltask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exp2.ExperimentalTask')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Quiz')),
            ],
            bases=('exp2.experimentaltask',),
        ),
    ]
